feat(UIKIT-766): Добавлен сервис Яндекс.Метрики
kaluga-astral/yandex-metric pull request #1
Opened 2023-05-31 08:43 UTC by StanislavDa

2023-05-31 10:24 UTC, AndTem requested changes

2023-05-31 10:24 UTC, AndTem commented on package/src/Metrika/Metrika.ts
> +export class Metrika {
YandexMetrica

2023-05-31 10:24 UTC, AndTem commented on package/src/Metrika/Metrika.ts
> +  docParams?: DocParams;
В постановке был spead.
Это означает, что все docParams должны быть в корне initParams

2023-05-31 10:24 UTC, AndTem commented on package/src/Metrika/Metrika.ts
> +   * @example Metrika.init({ counterID: 'XXXXXX', enabled: process.env.IS_PRODUCTION })
Не хватает описания того, какие параметры по дефолту проставляются

2023-05-31 10:24 UTC, AndTem commented on package/src/Metrika/Metrika.ts
> +      const unavailableError = 'Сервис Яндекс.Метрики недоступен';
Лучше создать ошибку и в консоле ее показывать, ее и прикидывать в onerror

2023-05-31 10:24 UTC, AndTem commented on package/src/Metrika/Metrika.ts
> +  private get metrika() {
Нужен коммент для чего этот геттер

2023-05-31 10:24 UTC, AndTem commented on package/src/Metrika/Metrika.ts
> +  private runCommand = (callback: () => void) => {
Нужно jsdoc описание

2023-05-31 10:24 UTC, AndTem commented on package/src/Metrika/Metrika.ts
> +    this.metrika(this.counterID, 'init', params);
В постановке написано, что сюда же можно прокинуть и userParams

2023-05-31 10:24 UTC, AndTem commented on package/src/Metrika/Metrika.ts
> +export type DocParams = {
Переименуй. Зачем указатель на доку

2023-05-31 10:24 UTC, AndTem commented on package/src/Metrika/Metrika.ts
> +    this.runCommand(() => this.metrika(this.counterID, 'addParam', params));
Не paramS?

2023-05-31 10:24 UTC, AndTem commented on package/src/Metrika/Metrika.ts
> +export type InitParams = {
Префикс добавь YandexMetricaInitParams

2023-06-01 11:51 UTC, AndTem requested changes

2023-06-01 11:51 UTC, AndTem commented on package/src/YandexMetrika/YandexMetrika.ts
> +    if (!Boolean(counterID)) {
Не уверен, что стоит ложить все приложение, если init зафейлился.
Сделай отправку в onError ошибки и в консоль вывод.
А еще тут надо проверять enabled, если false, то эти проверки не нужны

2023-06-01 11:51 UTC, AndTem commented on package/src/YandexMetrika/YandexMetrika.ts
> +   * @example YandexMetrika.reachGoal({ target: "XXXXXX", extra: { param: "values" } })
С маленькой буквы экземпляр пишется

2023-06-01 11:51 UTC, AndTem commented on package/src/YandexMetrika/YandexMetrika.ts
> +export class YandexMetrika {
Нужны тесты на то, что можно протестировать. ym мокать

2023-06-07 09:29 UTC, StanislavDa commented on package/src/YandexMetrika/YandexMetrika.ts
> +export class YandexMetrika {
а что тут можно протестировать?)

2023-06-08 08:09 UTC, AndTem commented on package/src/YandexMetrika/YandexMetrika.ts
> +export class YandexMetrika {
1. onError
2. Выключение методов, если enabled false

2023-06-08 08:40 UTC, AndTem commented on README.md
> +# Methods
Отсутствую разделы документации, описанные в [задаче](https://track.astral.ru/soft/browse/UIKIT-766)

2023-06-09 08:30 UTC, AndTem requested changes

2023-06-09 08:30 UTC, AndTem commented on package/src/YandexMetrika/YandexMetrika.test.ts
> +describe('YandexMetrika.init', () => {
Два одинаковых describe.
Надо просто в один describe положить два it

2023-06-09 08:54 UTC, AndTem submitted a review, later dismissed

2023-06-09 10:13 UTC, perevezencev approved these changes, later dismissed

2023-06-09 10:13 UTC, perevezencev commented on package/src/YandexMetrika/YandexMetrika.ts
> +const DEFAULT_DOC_PARAMS: YandexMetrikaParams = {
Почему DOC? Что это значит?

2023-06-09 10:40 UTC, merged